# Application does not use a database - all work is done on the front end
# Minimal database.yml to prevent ActiveRecord rake task errors
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ":memory:"

test:
  <<: *default
  database: ":memory:"

production:
  <<: *default
  database: ":memory:"
